version: "3"
services:
    www:
        restart: "always"
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    www2:
        restart: "always"
        build:
            dockerfile: Dockerfile.static
            context: .
        ports:
            - "8082:80"
        links:
            - db
        networks:
            - default
    db:
        restart: "always"
        image: mysql:8.0.16
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password','--secure-file-priv=/var/shared']
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - persistent:/var/lib/mysql
            - ./shared:/var/shared
        networks:
            - default
    phpmyadmin:
        restart: "always"
        image: phpmyadmin/phpmyadmin:4.8
        links:
            - db:db
        ports:
            - 8081:80
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - default
networks:
    default:
volumes:
    persistent: